# Generated by Django 4.1.7 on 2023-03-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_basic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic',
            name='images',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
