# Generated by Django 4.1.7 on 2023-03-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_remove_basic_images_basic_image_big_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='image_big',
            field=models.ImageField(default=0, upload_to='trade/'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='image_small',
            field=models.ImageField(default=0, upload_to='trade/'),
        ),
    ]
