# Generated by Django 4.1.7 on 2023-03-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_basic_image_big_alter_basic_image_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='image_big',
            field=models.FileField(default=0, upload_to='trade/'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='image_small',
            field=models.FileField(default=0, upload_to='trade/'),
        ),
    ]
