# Generated by Django 4.1.7 on 2023-03-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_alter_basic_image_big'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='image_big',
            field=models.ImageField(upload_to='trade/'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='image_small',
            field=models.ImageField(upload_to='trade/'),
        ),
    ]
